### **1. Linear Algebra**

#### (1) Basic Objects
- **Scalar**: single number, e.g. `x = 3`.
- **Vector**: 1-D array, e.g. `x = [1, 2, 3]`; often represents one sample or one feature list.
- **Matrix**: 2-D array, shape `(m, n)`; common for a batch of data or a linear transform.
- **Tensor**: general n-D array. In deep learning, images, batches, and model parameters are usually tensors.

Shape is important: most linear algebra bugs are shape mismatches.

#### (2) Matrix and Vector Operations
- **Elementwise operation**: same-shape tensors compute position by position, such as `A + B`, `A * B`.
- **Dot product**: for vectors `x, y`, `x^T y = sum_i x_i y_i`; measures similarity when vectors are normalized.
- **Matrix-vector product**: `A x` maps a vector to another vector.
- **Matrix-matrix product**: `A B` composes two linear transformations.
- **Transpose**: `A^T` swaps rows and columns.

For multiplication, inner dimensions must match: `(m, n) @ (n, k) -> (m, k)`.

#### (3) Reduction and Axis
A reduction summarizes tensor values, for example `sum`, `mean`, `max`.

- `sum(A)`: sum all elements.
- `sum(A, axis=0)`: reduce rows, keep one value for each column.
- `sum(A, axis=1)`: reduce columns, keep one value for each row.
- `keepdims=True`: keeps the reduced dimension, useful for broadcasting later.

#### (4) Broadcasting
Broadcasting lets tensors with compatible shapes participate in elementwise operations.

Example: if `A.shape = (3, 4)` and `b.shape = (4,)`, then `A + b` adds `b` to every row of `A`.

Rule of thumb: compare shapes from right to left; dimensions must be equal or one of them must be `1`.

#### (5) Norms
Norms measure the size of vectors or matrices.

- **L2 norm**: `||x||_2 = sqrt(sum_i x_i^2)`, common length measure.
- **L1 norm**: `||x||_1 = sum_i |x_i|`, often encourages sparsity.
- **Frobenius norm**: matrix norm, `||A||_F = sqrt(sum_ij A_ij^2)`.

In deep learning, norms appear in regularization, gradient clipping, and loss analysis.

#### (6) Why Linear Algebra Matters in Deep Learning
- A neural network layer often has the form `Y = XW + b`.
- Forward propagation is mostly tensor operations.
- Backpropagation computes gradients with respect to tensors.
- GPUs are efficient because large tensor/matrix operations can be parallelized.

Key habit: always track each tensor's shape before and after an operation.

### **2. Realization of Linear Algebra**

In [17]:
import torch

In [18]:
# Scalars are represented by tensors with only one element
x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [19]:
# Vectors can be viewed as lists of scalar values
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [20]:
# Access any element by indexing into the tensor
x[0]

tensor(0)

In [21]:
# Access the length of a tensor
len(x)

4

In [22]:
# Access the shape of a tensor
x.shape

torch.Size([4])

In [23]:
# Create an m x n matrix by specifying the two dimensions m and n
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [24]:
# Matrix transpose
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [25]:
# The transpose of a symmetric matrix is equal to itself
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [26]:
# Just as vectors generalize scalars and matrices generalize vectors, we can build data structures with multiple axes
x=torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [27]:
# Given any two tensors with the same shape, any elementwise binary operation returns a tensor with the same shape
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [28]:
# Elementwise multiplication of two matrices is called the Hadamard product, denoted by \odot in LaTeX
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [29]:
a=2
x=torch.arange(24).reshape(2,3,4)
a+x,(a*x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [30]:
# Calculate the sum of its elements
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [31]:
# Sum the elements of a tensor with any shape
A=torch.arange(20*2).reshape(2,5,4)
A.shape, A.sum(),A

(torch.Size([2, 5, 4]),
 tensor(780),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]))

In [32]:
# Specify the axis for summing a tensor; here A.shape=[2,5,4]
A_SUM_AXIS0=A.sum(axis=0)  # Sum corresponding elements across the batch/pages axis; the pages axis is reduced
A_SUM_AXIS0,A_SUM_AXIS0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [33]:
A_SUM_AXIS1=A.sum(axis=1) # Sum elements in the same column within each page; the rows axis is reduced
A_SUM_AXIS1,A_SUM_AXIS1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [34]:
# Sum along two dimensions
A.sum(axis=[0,1]).shape

torch.Size([4])

In [35]:
# A quantity related to summation: the mean
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [36]:
# Compute the mean along an axis
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [37]:
# Keep the axes unchanged when calculating the sum or mean
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [38]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [39]:
# Calculate the cumulative sum of A's elements along an axis
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [40]:
# The dot product is the sum of elementwise products at the same positions
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [41]:
# Express the dot product of two vectors by first multiplying elementwise and then summing
torch.sum(x*y)

tensor(6.)

In [42]:
# Matrix-vector multiplication
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [43]:
# Matrix-matrix multiplication
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [44]:
# The L1 norm is the sum of the absolute values of the vector elements
u=torch.tensor([3.0,-4.0])
torch.abs(u).sum()

tensor(7.)

In [45]:
# The L2 norm is the square root of the sum of squared vector elements
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [46]:
# The Frobenius norm is the square root of the sum of squared matrix elements
torch.norm(torch.ones((4,9)))

tensor(6.)

### **3. Derivative Calculation**

#### 3.1 Scalar Derivatives

##### (1) Derivatives of Common Functions

The table below lists the derivative formulas for several basic functions:

| Function $y$ | Derivative $\frac{dy}{dx}$ | Notes |
| :--- | :--- | :--- |
| $a$ | $0$ | $a$ is not a function of $x$ (i.e., $a$ is a constant) |
| $x^n$ | $n x^{n-1}$ | Power Rule |
| $\exp(x)$ | $\exp(x)$ | Exponential function |
| $\log(x)$ | $\frac{1}{x}$ | Logarithmic function |
| $\sin(x)$ | $\cos(x)$ | Trigonometric function (Sine) |

---

##### (2) Derivative Rules

The table below lists the rules for differentiation of sums, products, and composite functions:

| Function Form $y$ | Derivative $\frac{dy}{dx}$ | Rule Name |
| :--- | :--- | :--- |
| $u + v$ | $\frac{du}{dx} + \frac{dv}{dx}$ | **Sum Rule** |
| $uv$ | $\frac{du}{dx}v + \frac{dv}{dx}u$ | **Product Rule** |
| $y = f(u), u = g(x)$ | $\frac{dy}{du} \frac{du}{dx}$ | **Chain Rule** |

#### 3.2 Subderivatives

* **Concept:** Extending the notion of derivatives to non-differentiable functions.

##### Example 1: Absolute Value Function $y = |x|$

At the sharp corner $x = 0$, the function is not traditionally differentiable. However, we can define a subderivative at this point, which represents the slope of any line that touches the function at $x = 0$ and remains entirely below (or touching) it (e.g., slopes like $-0.3$ or $0.5$).

$$\frac{\partial |x|}{\partial x} = \begin{cases} 1 & \text{if } x > 0 \\ -1 & \text{if } x < 0 \\ a & \text{if } x = 0, \quad a \in [-1, 1] \end{cases}$$

---

##### Example 2: ReLU Function $\max(x, 0)$

Another common example is the Rectified Linear Unit (ReLU) function, which is non-differentiable at the kink where $x = 0$.

$$\frac{\partial}{\partial x} \max(x, 0) = \begin{cases} 1 & \text{if } x > 0 \\ 0 & \text{if } x < 0 \\ a & \text{if } x = 0, \quad a \in [0, 1] \end{cases}$$

#### 3.3 Advanced Vector and Matrix Derivatives

[Reference Tutorial Video (Chinese)](https://www.bilibili.com/video/BV1av4y1b7MM/)

##### 3.3.1 Crucial Concept: Numerator vs. Denominator Layout
When taking derivatives involving vectors and matrices, the shape of the resulting derivative depends entirely on the layout convention you choose. The slides primarily use the **Numerator Layout** , which is standard in most machine learning contexts.

* **Numerator Layout:** The derivative shape aligns with the *numerator* (the function $\mathbf{y}$). 
    * Derivative of a scalar $y$ w.r.t a column vector $\mathbf{x}$ is a **row vector** ($\frac{\partial y}{\partial \mathbf{x}}$ is $1 \times n$).
    * Derivative of a column vector $\mathbf{y}$ w.r.t a scalar $x$ is a **column vector** ($\frac{\partial \mathbf{y}}{\partial x}$ is $m \times 1$).
* **Denominator Layout:** The exact opposite. The derivative shape aligns with the *denominator* (the variable $\mathbf{x}$). In this layout, $\frac{\partial y}{\partial \mathbf{x}}$ would be a column vector.

> **Rule of Thumb for Numerator Layout:**
> If $\mathbf{y} \in \mathbb{R}^{m \times 1}$ and $\mathbf{x} \in \mathbb{R}^{n \times 1}$, the derivative $\frac{\partial \mathbf{y}}{\partial \mathbf{x}}$ will have the dimensions $m \times n$.

---

##### 3.3.2 Vector w.r.t Vector Derivatives (The Jacobian)
When you differentiate a vector function $\mathbf{y}$ ($m \times 1$) with respect to a vector $\mathbf{x}$ ($n \times 1$), the result is an $m \times n$ matrix called the **Jacobian Matrix**.

$$ 
\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}, \quad \mathbf{y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_m \end{bmatrix} 
$$

$$ 
\frac{\partial \mathbf{y}}{\partial \mathbf{x}} = 
\begin{bmatrix}
\frac{\partial y_1}{\partial x_1} & \frac{\partial y_1}{\partial x_2} & \dots & \frac{\partial y_1}{\partial x_n} \\
\frac{\partial y_2}{\partial x_1} & \frac{\partial y_2}{\partial x_2} & \dots & \frac{\partial y_2}{\partial x_n} \\
\vdots & \vdots & \ddots & \vdots \\
\frac{\partial y_m}{\partial x_1} & \frac{\partial y_m}{\partial x_2} & \dots & \frac{\partial y_m}{\partial x_n}
\end{bmatrix}
$$

---

##### 3.3.3 Rules and Examples for Vector Derivatives
Given vectors $\mathbf{x} \in \mathbb{R}^n$, $\mathbf{y} \in \mathbb{R}^m$, constant vector $\mathbf{a}$, constant matrix $\mathbf{A}$, and vector functions $\mathbf{u}, \mathbf{v}$:

| Function $\mathbf{y}$ | Derivative $\frac{\partial \mathbf{y}}{\partial \mathbf{x}} \in \mathbb{R}^{m \times n}$ | Notes |
| :--- | :--- | :--- |
| $\mathbf{a}$ | $\mathbf{0}$ | $\mathbf{a}$ is not a function of $\mathbf{x}$. Result is a zero matrix. |
| $\mathbf{x}$ | $\mathbf{I}$ | The derivative of $\mathbf{x}$ w.r.t itself is the Identity matrix. |
| $\mathbf{Ax}$ | $\mathbf{A}$ | Linear transformation. |
| $\mathbf{x}^T\mathbf{A}$ | $\mathbf{A}^T$ | Transposed linear transformation. |
| $a\mathbf{u}$ | $a \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$ | Constant scalar multiple rule. |
| $\mathbf{Au}$ | $\mathbf{A} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$ | Constant matrix multiple rule. |
| $\mathbf{u} + \mathbf{v}$ | $\frac{\partial \mathbf{u}}{\partial \mathbf{x}} + \frac{\partial \mathbf{v}}{\partial \mathbf{x}}$ | Sum rule. |

---

##### 3.3.4 Expanding Dimensions: Scalar, Vector, and Matrix Rules
The table below summarizes the output dimensions when calculating derivatives across scalars ($x, y$), column vectors ($\mathbf{x}, \mathbf{y}$), and matrices ($\mathbf{X}, \mathbf{Y}$). 

*(Assuming Numerator Layout)*

| Denominator (Variable) $\rightarrow$<br>Numerator (Function) $\downarrow$ | Scalar $x$<br>Shape: $(1, 1)$ | Vector $\mathbf{x}$<br>Shape: $(n, 1)$ | Matrix $\mathbf{X}$<br>Shape: $(n, k)$ |
| :--- | :--- | :--- | :--- |
| **Scalar $y$** Shape: $(1, 1)$ | $\frac{\partial y}{\partial x}$ <br> Shape: $(1, 1)$ | $\frac{\partial y}{\partial \mathbf{x}}$ <br> Shape: $(1, n)$ | $\frac{\partial y}{\partial \mathbf{X}}$ <br> Shape: $(k, n)$ *(Note the transpose)* |
| **Vector $\mathbf{y}$** Shape: $(m, 1)$ | $\frac{\partial \mathbf{y}}{\partial x}$ <br> Shape: $(m, 1)$ | $\frac{\partial \mathbf{y}}{\partial \mathbf{x}}$ <br> Shape: $(m, n)$ | $\frac{\partial \mathbf{y}}{\partial \mathbf{X}}$ <br> Shape: $(m, k, n)$ *(3D Tensor)* |
| **Matrix $\mathbf{Y}$** Shape: $(m, l)$ | $\frac{\partial \mathbf{Y}}{\partial x}$ <br> Shape: $(m, l)$ | $\frac{\partial \mathbf{Y}}{\partial \mathbf{x}}$ <br> Shape: $(m, l, n)$ *(3D Tensor)*| $\frac{\partial \mathbf{Y}}{\partial \mathbf{X}}$ <br> Shape: $(m, l, k, n)$ *(4D Tensor)*|

> **Note on Higher Dimensions:** Differentiating a vector w.r.t a matrix, or a matrix w.r.t a matrix, results in multidimensional arrays (Tensors). For practical neural network implementation (like backpropagation), these are usually flattened or handled via specific matrix multiplication rules rather than computing the full 4D tensor.

#### 3.4 Vector Chain Rule

[Reference Tutorial Video (Chinese)](https://www.bilibili.com/video/BV1po4y1J7wp/)

##### 3.4.1 Scalar Chain Rule
For scalar variables $y$, $u$, and $x$, where $y = f(u)$ and $u = g(x)$:

$$\frac{\partial y}{\partial x} = \frac{\partial y}{\partial u} \frac{\partial u}{\partial x}$$

---

##### 3.4.2 Extension to Vectors
When extending to vectors, this note adopts the **Numerator Layout** (Jacobian formulation), where the derivative of a scalar with respect to a column vector is represented as a row vector.

###### Case 1: Scalar $\rightarrow$ Scalar $\rightarrow$ Vector
* **Variables:** Scalar $y$, Scalar $u$, Vector $\mathbf{x} \in \mathbb{R}^n$
* **Formula:** $$\frac{\partial y}{\partial \mathbf{x}} = \frac{\partial y}{\partial u} \frac{\partial u}{\partial \mathbf{x}}$$
* **Dimensions:** $(1,n) = (1,1) \times (1,n)$

###### Case 2: Scalar $\rightarrow$ Vector $\rightarrow$ Vector
* **Variables:** Scalar $y$, Vector $\mathbf{u} \in \mathbb{R}^k$, Vector $\mathbf{x} \in \mathbb{R}^n$
* **Formula:** $$\frac{\partial y}{\partial \mathbf{x}} = \frac{\partial y}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$
* **Dimensions:** $(1,n) = (1,k) \times (k,n)$

###### Case 3: Vector $\rightarrow$ Vector $\rightarrow$ Vector
* **Variables:** Vector $\mathbf{y} \in \mathbb{R}^m$, Vector $\mathbf{u} \in \mathbb{R}^k$, Vector $\mathbf{x} \in \mathbb{R}^n$
* **Formula:** $$\frac{\partial \mathbf{y}}{\partial \mathbf{x}} = \frac{\partial \mathbf{y}}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$
* **Dimensions:** $(m,n) = (m,k) \times (k,n)$

---

##### 3.4.3 Derivation of the Vector Chain Rule

To understand why matrix multiplication works seamlessly here, let's derive **Case 2** and **Case 3** using a component-wise approach.

###### Derivation for Case 2 (Scalar-Vector-Vector)
Let $y$ be a scalar function of vector $\mathbf{u} = [u_1, u_2, \dots, u_k]^T$, and let $\mathbf{u}$ be a function of vector $\mathbf{x} = [x_1, x_2, \dots, x_n]^T$.

By the total derivative rule in multivariate calculus, the partial derivative of $y$ with respect to a single component $x_j$ is the sum of the partial derivatives through all intermediate paths $u_i$:

$$\frac{\partial y}{\partial x_j} = \sum_{i=1}^{k} \frac{\partial y}{\partial u_i} \frac{\partial u_i}{\partial x_j}$$

Now, let's look at the definitions of the vector derivatives under the numerator layout:
1. $\frac{\partial y}{\partial \mathbf{x}}$ is a $1 \times n$ row vector:
   $$\frac{\partial y}{\partial \mathbf{x}} = \begin{bmatrix} \frac{\partial y}{\partial x_1} & \frac{\partial y}{\partial x_2} & \dots & \frac{\partial y}{\partial x_n} \end{bmatrix}$$

2. $\frac{\partial y}{\partial \mathbf{u}}$ is a $1 \times k$ row vector:
   $$\frac{\partial y}{\partial \mathbf{u}} = \begin{bmatrix} \frac{\partial y}{\partial u_1} & \frac{\partial y}{\partial u_2} & \dots & \frac{\partial y}{\partial u_k} \end{bmatrix}$$

3. $\frac{\partial \mathbf{u}}{\partial \mathbf{x}}$ is a $k \times n$ Jacobian matrix:
   $$\frac{\partial \mathbf{u}}{\partial \mathbf{x}} = \begin{bmatrix} \frac{\partial u_1}{\partial x_1} & \frac{\partial u_1}{\partial x_2} & \dots & \frac{\partial u_1}{\partial x_n} \\ \frac{\partial u_2}{\partial x_1} & \frac{\partial u_2}{\partial x_2} & \dots & \frac{\partial u_2}{\partial x_n} \\ \vdots & \vdots & \ddots & \vdots \\ \frac{\partial u_k}{\partial x_1} & \frac{\partial u_k}{\partial x_2} & \dots & \frac{\partial u_k}{\partial x_n} \end{bmatrix}$$

If we perform the matrix multiplication $\frac{\partial y}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$, the $j$-th entry of the resulting row vector is the dot product of $\frac{\partial y}{\partial \mathbf{u}}$ and the $j$-th column of $\frac{\partial \mathbf{u}}{\partial \mathbf{x}}$:

$$\left( \frac{\partial y}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}} \right)_j = \begin{bmatrix} \frac{\partial y}{\partial u_1} & \dots & \frac{\partial y}{\partial u_k} \end{bmatrix} \begin{bmatrix} \frac{\partial u_1}{\partial x_j} \\ \vdots \\ \frac{\partial u_k}{\partial x_j} \end{bmatrix} = \sum_{i=1}^{k} \frac{\partial y}{\partial u_i} \frac{\partial u_i}{\partial x_j}$$

This matches our component-wise total derivative exactly. Therefore:
$$\frac{\partial y}{\partial \mathbf{x}} = \frac{\partial y}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$

---

###### Derivation for Case 3 (Vector-Vector-Vector)
Now, let $\mathbf{y} = [y_1, y_2, \dots, y_m]^T$ be a vector. Each component $y_i$ is a scalar function of $\mathbf{u}$, which in turn depends on $\mathbf{x}$.

Applying Case 2 to each component $y_i$ individually, we get a system of row vector equations:

$$\frac{\partial y_1}{\partial \mathbf{x}} = \frac{\partial y_1}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$
$$\frac{\partial y_2}{\partial \mathbf{x}} = \frac{\partial y_2}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$
$$\vdots$$
$$\frac{\partial y_m}{\partial \mathbf{x}} = \frac{\partial y_m}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$

Stacking these row vector equations vertically to form the $m \times n$ Jacobian matrix $\frac{\partial \mathbf{y}}{\partial \mathbf{x}}$:

$$\begin{bmatrix} \frac{\partial y_1}{\partial \mathbf{x}} \\ \frac{\partial y_2}{\partial \mathbf{x}} \\ \vdots \\ \frac{\partial y_m}{\partial \mathbf{x}} \end{bmatrix} = \begin{bmatrix} \frac{\partial y_1}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}} \\ \frac{\partial y_2}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}} \\ \vdots \\ \frac{\partial y_m}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}} \end{bmatrix}$$

We can factor out the matrix $\frac{\partial \mathbf{u}}{\partial \mathbf{x}}$ to the right:

$$\begin{bmatrix} \frac{\partial y_1}{\partial \mathbf{x}} \\ \frac{\partial y_2}{\partial \mathbf{x}} \\ \vdots \\ \frac{\partial y_m}{\partial \mathbf{x}} \end{bmatrix} = \begin{bmatrix} \frac{\partial y_1}{\partial \mathbf{u}} \\ \frac{\partial y_2}{\partial \mathbf{u}} \\ \vdots \\ \frac{\partial y_m}{\partial \mathbf{u}} \end{bmatrix} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$

By definition, the matrix on the left side is $\frac{\partial \mathbf{y}}{\partial \mathbf{x}}$, and the matrix being multiplied on the right side is $\frac{\partial \mathbf{y}}{\partial \mathbf{u}}$. Thus, we arrive at the final vector chain rule formula:

$$\frac{\partial \mathbf{y}}{\partial \mathbf{x}} = \frac{\partial \mathbf{y}}{\partial \mathbf{u}} \frac{\partial \mathbf{u}}{\partial \mathbf{x}}$$

#### 3.5 Automatic Differentiation (Autograd) and Computational Graphs

##### 3.5.1 Introduction to Autograd
In deep learning, training neural networks requires calculating the gradients of a loss function with respect to the model's parameters (weights). Doing this manually for complex models is extremely tedious and error-prone. **Automatic Differentiation** solves this by automatically computing these gradients using the **chain rule** from calculus.

##### 3.5.2 The Core Concept: Computational Graphs
To perform automatic differentiation, frameworks represent computations as **Directed Acyclic Graphs (DAGs)**. 
- **Nodes** represent variables (tensors/matrices) or parameters.
- **Edges** represent mathematical operations (operators like addition, multiplication).

###### Example Breakdown
Consider the loss function: `z = (<x, w> - y)^2`
The framework decomposes this into smaller, manageable operators:
1. `a = <x, w>` (Dot product of input `x` and weights `w`)
2. `b = a - y` (Subtract true label `y`)
3. `z = b^2` (Square the result)

During the **forward pass**, the system calculates and stores the intermediate values (`a`, `b`, `z`). During the **backward pass**, it traverses the graph in reverse to calculate the gradients of `z` with respect to `x` and `w` using the stored values.

##### 3.5.3 Two Paradigms of Graph Construction

###### A. Explicit Construction (Static Graphs)
- **Concept:** You first define the entire computational graph structure (variables and operations) without passing any actual data. Once the graph is defined, you bind data to it and execute it.
- **Examples:** Early TensorFlow, Theano, MXNet (`mxnet.sym`).
- **Pros:** Highly optimizable by the compiler (faster execution, better memory management).
- **Cons:** Harder to debug, less flexible with dynamic control flows (like Python `if` or `for` loops).

###### B. Implicit Construction (Dynamic Graphs)
- **Concept:** The computational graph is built on-the-fly as the actual operations are executed in your code.
- **Examples:** PyTorch, MXNet (`mxnet.autograd`).
- **Pros:** Extremely developer-friendly. It feels like writing standard Python code. Easy to debug using standard Python tools (like `print` statements).
- **Cons:** Slightly harder for the underlying engine to perform global optimizations compared to static graphs.

#### 3.6 Two Modes of Automatic Differentiation

* **Chain Rule:**
    $$\frac{\partial y}{\partial x} = \frac{\partial y}{\partial u_n} \frac{\partial u_n}{\partial u_{n-1}} \dots \frac{\partial u_2}{\partial u_1} \frac{\partial u_1}{\partial x}$$

* **Forward Accumulation:**
    $$\frac{\partial y}{\partial x} = \frac{\partial y}{\partial u_n} \left( \frac{\partial u_n}{\partial u_{n-1}} \left( \dots \left( \frac{\partial u_2}{\partial u_1} \frac{\partial u_1}{\partial x} \right) \right) \right)$$

* **Reverse Accumulation (also known as Backpropagation):**
    $$\frac{\partial y}{\partial x} = \left( \left( \left( \frac{\partial y}{\partial u_n} \frac{\partial u_n}{\partial u_{n-1}} \right) \dots \right) \frac{\partial u_2}{\partial u_1} \right) \frac{\partial u_1}{\partial x}$$

##### 3.7 Complexity

* **Computational complexity:** O(n), where n is the number of operators
  * Usually, the computational costs of the forward and backward passes are similar
* **Memory complexity:** O(n), because all intermediate results from the forward pass need to be stored
* **Compared with forward accumulation:**
  * O(n) computational complexity is required to compute the gradient of a single variable
  * O(1) memory complexity

#### 4. Implementation of Autograd
**Example:**
$$y = 2\mathbf{x}^\top\mathbf{x}$$

In [47]:
import torch

x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [48]:
# Before calculating the gradient of y with respect to x, allocate space to store the gradient
x.requires_grad_(True)  # Equivalent to x=torch.arange(4.0, requires_grad=True)
x.grad # The default value is None

In [49]:
# Calculate y
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [50]:
# Call backward to automatically compute the gradient of y with respect to each element of x
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [51]:
x.grad==4*x

tensor([True, True, True, True])

In [52]:
# Calculate another function of x
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [53]:
# Calling backward on a non-scalar requires a gradient argument that specifies the differential function
x.grad.zero_()
y=x*x
# Equivalent to y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [55]:
# Move some computations outside the recorded computational graph
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

##### 4.1 A More Intuitive View of `backward()` and `zero_()`

A simple way to understand `backward()` is: **start from the final result and ask how much each input affects it.**

Consider this code:

```python
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
```

Suppose:

```python
x = tensor([0., 1., 2., 3.])
```

Then:

```python
y = x * x
# y = tensor([0., 1., 4., 9.])
```

Next:

```python
u = y.detach()
```

`u` still has the values `[0, 1, 4, 9]`, but PyTorch treats `u` as a fixed constant when computing gradients. In other words, even though the values in `u` came from `x * x`, `detach()` tells PyTorch not to trace back through how `u` was created.

Now:

```python
z = u * x
```

From PyTorch's point of view, this looks like:

$$
z = [0x_1,\ 1x_2,\ 4x_3,\ 9x_4]
$$

`z` is a vector. To call `backward()`, we usually turn it into a scalar first:

```python
z.sum()
```

That is:

$$
L = 0x_1 + 1x_2 + 4x_3 + 9x_4
$$

Then:

```python
z.sum().backward()
```

This means: ask PyTorch to compute the partial derivative of the final result $L$ with respect to each element in `x`.

Because:

$$
\frac{\partial L}{\partial x_1}=0,\quad
\frac{\partial L}{\partial x_2}=1,\quad
\frac{\partial L}{\partial x_3}=4,\quad
\frac{\partial L}{\partial x_4}=9
$$

So:

```python
x.grad
# tensor([0., 1., 4., 9.])
```

This is exactly equal to `u`, so:

```python
x.grad == u
```

returns `tensor([True, True, True, True])`.

Now consider `zero_()`. Think of `x.grad` as a box that stores gradients. Each time PyTorch runs `backward()`, it does not throw away the old values in the box. Instead, it adds the new gradient to the old gradient. So before computing a fresh gradient, we usually clear it first:

```python
x.grad.zero_()
```

The trailing `_` means this is an in-place operation: it directly changes the values inside the `x.grad` tensor to 0.


In [57]:
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

In [59]:
# We can still compute gradients even when the computational graph is built through Python control flow, such as conditionals, loops, or arbitrary function calls
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a=torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

a.grad==d/a

tensor(True)