### **1. Linear Algebra**

#### (1) Basic Objects
- **Scalar**: single number, e.g. `x = 3`.
- **Vector**: 1-D array, e.g. `x = [1, 2, 3]`; often represents one sample or one feature list.
- **Matrix**: 2-D array, shape `(m, n)`; common for a batch of data or a linear transform.
- **Tensor**: general n-D array. In deep learning, images, batches, and model parameters are usually tensors.

Shape is important: most linear algebra bugs are shape mismatches.

#### (2) Matrix and Vector Operations
- **Elementwise operation**: same-shape tensors compute position by position, such as `A + B`, `A * B`.
- **Dot product**: for vectors `x, y`, `x^T y = sum_i x_i y_i`; measures similarity when vectors are normalized.
- **Matrix-vector product**: `A x` maps a vector to another vector.
- **Matrix-matrix product**: `A B` composes two linear transformations.
- **Transpose**: `A^T` swaps rows and columns.

For multiplication, inner dimensions must match: `(m, n) @ (n, k) -> (m, k)`.

#### (3) Reduction and Axis
A reduction summarizes tensor values, for example `sum`, `mean`, `max`.

- `sum(A)`: sum all elements.
- `sum(A, axis=0)`: reduce rows, keep one value for each column.
- `sum(A, axis=1)`: reduce columns, keep one value for each row.
- `keepdims=True`: keeps the reduced dimension, useful for broadcasting later.

#### (4) Broadcasting
Broadcasting lets tensors with compatible shapes participate in elementwise operations.

Example: if `A.shape = (3, 4)` and `b.shape = (4,)`, then `A + b` adds `b` to every row of `A`.

Rule of thumb: compare shapes from right to left; dimensions must be equal or one of them must be `1`.

#### (5) Norms
Norms measure the size of vectors or matrices.

- **L2 norm**: `||x||_2 = sqrt(sum_i x_i^2)`, common length measure.
- **L1 norm**: `||x||_1 = sum_i |x_i|`, often encourages sparsity.
- **Frobenius norm**: matrix norm, `||A||_F = sqrt(sum_ij A_ij^2)`.

In deep learning, norms appear in regularization, gradient clipping, and loss analysis.

#### (6) Why Linear Algebra Matters in Deep Learning
- A neural network layer often has the form `Y = XW + b`.
- Forward propagation is mostly tensor operations.
- Backpropagation computes gradients with respect to tensors.
- GPUs are efficient because large tensor/matrix operations can be parallelized.

Key habit: always track each tensor's shape before and after an operation.

### **2. Realization of Linear Algebra**

In [30]:
import torch

In [31]:
# Scalars are represented by tensors with only one element
x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [32]:
# Vectors can be viewed as lists of scalar values
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [33]:
# Access any element by indexing into the tensor
x[0]

tensor(0)

In [34]:
# Access the length of a tensor
len(x)

4

In [35]:
# Access the shape of a tensor
x.shape

torch.Size([4])

In [36]:
# Create an m x n matrix by specifying the two dimensions m and n
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [37]:
# Matrix transpose
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [38]:
# The transpose of a symmetric matrix is equal to itself
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [39]:
# Just as vectors generalize scalars and matrices generalize vectors, we can build data structures with multiple axes
x=torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [40]:
# Given any two tensors with the same shape, any elementwise binary operation returns a tensor with the same shape
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [41]:
# Elementwise multiplication of two matrices is called the Hadamard product, denoted by \odot in LaTeX
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [42]:
a=2
x=torch.arange(24).reshape(2,3,4)
a+x,(a*x).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [43]:
# Calculate the sum of its elements
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [50]:
# Sum the elements of a tensor with any shape
A=torch.arange(20*2).reshape(2,5,4)
A.shape, A.sum(),A

(torch.Size([2, 5, 4]),
 tensor(780),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]))

In [ ]:
# Specify the axis for summing a tensor; here A.shape=[2,5,4]
A_SUM_AXIS0=A.sum(axis=0)  # Sum corresponding elements across the batch/pages axis; the pages axis is reduced
A_SUM_AXIS0,A_SUM_AXIS0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 torch.Size([5, 4]))

In [ ]:
A_SUM_AXIS1=A.sum(axis=1) # Sum elements in the same column within each page; the rows axis is reduced
A_SUM_AXIS1,A_SUM_AXIS1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [47]:
# Sum along two dimensions
A.sum(axis=[0,1]).shape

torch.Size([4])

In [57]:
# A quantity related to summation: the mean
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [ ]:
# Compute the mean along an axis
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [59]:
# Keep the axes unchanged when calculating the sum or mean
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [60]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [61]:
# Calculate the cumulative sum of A's elements along an axis
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [62]:
# The dot product is the sum of elementwise products at the same positions
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [64]:
# Express the dot product of two vectors by first multiplying elementwise and then summing
torch.sum(x*y)

tensor(6.)

In [ ]:
# Matrix-vector multiplication
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [66]:
# Matrix-matrix multiplication
B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [69]:
# The L1 norm is the sum of the absolute values of the vector elements
u=torch.tensor([3.0,-4.0])
torch.abs(u).sum()

tensor(7.)

In [67]:
# The L2 norm is the square root of the sum of squared vector elements
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [70]:
# The Frobenius norm is the square root of the sum of squared matrix elements
torch.norm(torch.ones((4,9)))

tensor(6.)